(() => {
  'use strict';
  const $ = (s, r = document) => r.querySelector(s);
  const $$ = (s, r = document) => [...r.querySelectorAll(s)];
  const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
  const header = $('#header');

  /* ---------- Count-up ---------- */
  const fmt = (v, dec, plain) => plain ? String(Math.round(v)) : v.toLocaleString('ko-KR', { minimumFractionDigits: dec, maximumFractionDigits: dec });
  function run(el, end, from, dec, plain, dur = 1600) {
    if (reduced) { el.textContent = fmt(end, dec, plain); return; }
    const t0 = performance.now();
    const tick = now => {
      const p = Math.min((now - t0) / dur, 1), e = 1 - Math.pow(1 - p, 4);
      el.textContent = fmt(from + (end - from) * e, dec, plain);
      if (p < 1) requestAnimationFrame(tick);
    };
    requestAnimationFrame(tick);
  }
  function countUp(el) {
    if (el.dataset.done) return; el.dataset.done = 1;
    run(el, parseFloat(el.dataset.count), parseFloat(el.dataset.from || 0), +(el.dataset.dec || 0), !!el.dataset.plain, +el.dataset.dur || 1600);
  }
  const countIO = 'IntersectionObserver' in window ? new IntersectionObserver(es => es.forEach(e => {
    if (e.isIntersecting) { countUp(e.target); countIO.unobserve(e.target); }
  }), { threshold: .4 }) : null;
  $$('[data-count]').forEach(el => countIO ? countIO.observe(el) : countUp(el));

  // Table numbers (generated by app.js) count up when visible and on every filter change
  const body = $('#portfolio-body'), foot = $('#portfolio-total'), tableBox = $('.table-scroll');
  let tableSeen = false;
  const animateTable = () => $$('td.number', tableBox).forEach(td => {
    const t = td.textContent.trim();
    if (/^[\d,]+$/.test(t)) run(td, parseInt(t.replace(/,/g, ''), 10), 0, 0, false, 1100);
  });
  if (tableBox && countIO) {
    new IntersectionObserver((es, o) => { if (es[0].isIntersecting) { tableSeen = true; animateTable(); o.disconnect(); } }, { threshold: .25 }).observe(tableBox);
    [body, foot].forEach(n => n && new MutationObserver(() => { if (tableSeen) animateTable(); }).observe(n, { childList: true }));
  }

  /* ---------- Tabs ---------- */
  $$('[data-tabs]').forEach(root => {
    const tabs = $$('[role=tab]', root), panels = tabs.map(t => document.getElementById(t.dataset.tab));
    const select = tab => tabs.forEach((t, i) => {
      const on = t === tab;
      t.setAttribute('aria-selected', on); t.tabIndex = on ? 0 : -1; panels[i].hidden = !on;
      if (on) $$('[data-count]', panels[i]).forEach(countUp);
    });
    tabs.forEach((t, i) => {
      t.addEventListener('click', () => select(t));
      t.addEventListener('keydown', e => {
        const d = { ArrowRight: 1, ArrowLeft: -1 }[e.key]; if (!d) return;
        const n = tabs[(i + d + tabs.length) % tabs.length]; select(n); n.focus();
      });
    });
  });

  /* ---------- Scroll reveal + stagger ---------- */
  const groups = ['.hero-copy', '.hl-row', '.about-points', '.values-grid', '.timeline', '.roadmap', '.phil-cards', '.rail', '.aum-objectives', '.step-stack', '.accordion', '.value-up-grid', '.people-grid', '.org-grid', '.compliance-grid', '.contact-details', '.actual-data', '.esg-grid', '.hero-grid', '.footer-top', '.film-copy', '.hero-chips'];
  const singles = ['.section-top', '.hl-head', '.section-heading', '.about-heading', '.about-copy>.lead', '.about-copy>p', '.vision-band', '.sticky-col', '.risk-panel>div', '.subsection>.eyebrow', '.subsection>.h3-large', '.table-toolbar', '#portfolio-filters', '.table-scroll', '.data-caution', '.quote-mark', '.phil-sticky h2', '.quote-credit', '.philosophy-aside', '.organization>h3', '.disclosure-controls', '.compliance-grid', '.esg-content>*', '.contact h2', '.contact-grid>div>p', '.contact .button', '.investment-notice'];
  if (!reduced && 'IntersectionObserver' in window) {
    const mark = (el, i) => { if (el.classList.contains('r')) return; el.classList.add('r'); el.style.setProperty('--d', (i * 0.12).toFixed(2) + 's'); io.observe(el); };
    const io = new IntersectionObserver(es => es.forEach(e => {
      if (e.isIntersecting) { e.target.classList.add('in'); io.unobserve(e.target); }
    }), { threshold: .12, rootMargin: '0px 0px -6% 0px' });
    singles.forEach(s => $$(s).forEach((el, i) => mark(el, s.includes('>') && !s.endsWith('>*') ? 0 : (s.endsWith('>*') ? i : 0))));
    groups.forEach(g => $$(g).forEach(parent => [...parent.children].forEach((el, i) => { if (!el.matches('.hero-visual')) mark(el, Math.min(i, 8)); })));
    $$('.hero-visual').forEach(el => mark(el, 3));
  }

  /* ---------- Parallax ---------- */
  const px = !reduced ? $$('[data-parallax]') : [];
  let ticking = false;
  const heroCopy = $('.hero-copy'), heroChips = $('.hero-chips');
  const parallax = () => {
    ticking = false;
    const vh = innerHeight, y = scrollY;
    if (heroCopy) {
      const k = Math.max(0, 1 - y / (vh * .62));
      heroCopy.style.opacity = k; heroChips.style.opacity = k;
      if (!reduced) { heroCopy.style.translate = '0 ' + (-y * .14).toFixed(1) + 'px'; heroChips.style.translate = '0 ' + (-y * .24).toFixed(1) + 'px'; }
    }
    px.forEach(el => {
      const r = el.parentElement.getBoundingClientRect();
      if (r.bottom < -200 || r.top > vh + 200) return;
      const off = (r.top + r.height / 2 - vh / 2) * parseFloat(el.dataset.parallax);
      el.style.setProperty('--p', off.toFixed(1) + 'px');
    });
  };

  /* ---------- Scroll: progress, parallax, dynamic GNB ---------- */
  const bar = $('#progress-bar');
  let lastY = scrollY, hidden = false;
  const setHidden = v => { if (v !== hidden) { hidden = v; header.classList.toggle('nav-hide', v); } };
  const onScroll = () => {
    const h = document.documentElement, y = h.scrollTop;
    bar.style.transform = 'scaleX(' + y / (h.scrollHeight - h.clientHeight || 1) + ')';
    const dy = y - lastY;
    if (!header.classList.contains('menu-open')) {
      if (y < 120 || dy < -6) setHidden(false);
      else if (dy > 6) setHidden(true);
    }
    if (Math.abs(dy) > 6) lastY = y; else if (y < 120) lastY = y;
    if (!ticking) { ticking = true; requestAnimationFrame(parallax); }
  };
  addEventListener('scroll', onScroll, { passive: true });
  addEventListener('resize', parallax);
  parallax(); onScroll();
  header.addEventListener('focusin', () => setHidden(false));
  addEventListener('pointermove', e => {
    if (innerWidth > 960 && e.clientY > innerHeight - 110) setHidden(false);
    else if (innerWidth <= 960 && e.clientY < 90) setHidden(false);
  }, { passive: true });

  /* ---------- Video playback: play only in view, respect motion toggle ---------- */
  const vids = $('video');
  const stopped = () => reduced || document.body.classList.contains('motion-paused');
  if (vids.length && 'IntersectionObserver' in window) {
    const vio = new IntersectionObserver(es => es.forEach(e => {
      const v = e.target; v.dataset.vis = e.isIntersecting ? 1 : '';
      if (e.isIntersecting && !stopped()) v.play().catch(() => {}); else v.pause();
    }), { threshold: .05 });
    vids.forEach(v => vio.observe(v));
    new MutationObserver(() => vids.forEach(v => { if (stopped()) v.pause(); else if (v.dataset.vis) v.play().catch(() => {}); })).observe(document.body, { attributes: true, attributeFilter: ['class'] });
  }

  /* ---------- Strategy rail ---------- */
  const rail = $('#strategy-rail');
  if (rail) {
    const step = () => (rail.querySelector('.strategy-card')?.offsetWidth || 360) + 20;
    $('#rail-prev').addEventListener('click', () => rail.scrollBy({ left: -step(), behavior: 'smooth' }));
    $('#rail-next').addEventListener('click', () => rail.scrollBy({ left: step(), behavior: 'smooth' }));
    let down = false, sx = 0, sl = 0, moved = false;
    rail.addEventListener('pointerdown', e => { if (e.pointerType !== 'mouse') return; down = true; moved = false; sx = e.clientX; sl = rail.scrollLeft; });
    addEventListener('pointermove', e => { if (!down) return; const dx = e.clientX - sx; if (Math.abs(dx) > 5) moved = true; rail.scrollLeft = sl - dx; });
    addEventListener('pointerup', () => { down = false; });
    rail.addEventListener('click', e => { if (moved) { e.stopPropagation(); e.preventDefault(); moved = false; } }, true);
  }

  /* ---------- Card sheen follows cursor ---------- */
  document.addEventListener('pointermove', e => {
    const t = e.target.closest && e.target.closest('.glass');
    if (!t) return;
    const r = t.getBoundingClientRect();
    t.style.setProperty('--mx', (e.clientX - r.left) + 'px');
    t.style.setProperty('--my', (e.clientY - r.top) + 'px');
  }, { passive: true });
})();
